### ISSUE TITLE
Traincraft not compatible with Tinkers construct

### ISSUE THREAD

**Issue by Nightblade765** [EternalBlueFlame/Traincraft-5#170]
Somehow when i put traincraft in my modpack, it crashes and in the log i can see that it conflicts with T construct, any ideas how to fix that ?

**Comment by NitroxydeX** [comment]
paste the crashlog on pastebin and link it here. We had this discussion on the forums already. Traincraft works fine with Tinkers Construct

**Comment by EternalBlueFlame** [comment]
Probably a Tinker's issue, works fine for me, but send us the error log anyway, we may be able to help.
![javaw_2016-09-21_10-35-34](https://cloud.githubusercontent.com/assets/9969122/18717943/5e01dcf6-7fe7-11e6-8c3e-6a19022c33b4.png)

**Comment by Nightblade765** [comment]
You were right guys, it was just a random crash, it actually works fine after couple of tries, thanks for the help anyway :D

**Comment by canitzp** [comment]
@Nightblade765 can you please post the crash report, a random crash is most related to a mod and it would be nice when we know that this mod isn't Traincraft. If it isn't Traincraft I report the crash to the mod author of the crashing mod

**Comment by jimmykotaro** [comment]
Hello I have a problem with TrainCraft and Tinkers I think
when I add traincraft minecraft crashed

this is the crash

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 16/10/16 04:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.tools.ToolCore
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 35 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 37 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 41 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 429085016 bytes (409 MB) / 934805504 bytes (891 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_C1 59 mods loaded, 59 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UC  Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UC  CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
    UC  lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) 
    UC  deconstruction{2.2.5} [The Deconstruction Mod]([MC1.7.10]deconstruction[v2.2.5].jar) 
    UC  abyssalcraft{1.9.1.2} [AbyssalCraft](AbyssalCraft-1.7.10-1.9.1.2-FINAL.jar) 
    UC  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UC  adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8c.jar) 
    UC  AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
    UC  AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
    UC  AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
    UC  AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
    UC  AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
    UC  nevermine{2.3} [AdventOfAscension](AoA-2.4.B.jar) 
    UC  Aquaculture{1.2.3} [Aquaculture](Aquaculture-1.7.10-1.2.5.8.jar) 
    UC  BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar) 
    UC  Botania{r1.8-247} [Botania](Botania r1.8-247.jar) 
    UC  chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
    UC  DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage Indicators 1.7.10.jar) 
    UC  elementalcreepers{4.3.0} [Elemental Creepers](Elemental Creepers-universal_1.7.10-4.3.0.jar) 
    UC  eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UC  evilcraft{0.9.3} [EvilCraft](EvilCraft-1.7.10-0.9.3.jar) 
    UC  GraveStone{2.16.0} [GraveStone](GraveStone-2.16.0.jar) 
    UC  GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.2.7.jar) 
    UC  hammertime{Hammer Time-1.7.10-1.3.6} [Hammer Time!](HammerTime-1.3.6.jar) 
    UC  InfernalMobs{1.6.6} [Infernal Mobs](InfernalMobs-1.7.10.jar) 
    UC  malisiscore{1.7.10-0.14.3} [MalisisCore](malisiscore-1.7.10-0.14.3.jar) 
    UC  malisisdoors{1.7.10-1.13.2} [Malisis' Doors](malisisdoors-1.7.10-1.13.2.jar) 
    UC  Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UC  RadixCore{2.1.3} [RadixCore](RadixCore-1.7.10-2.1.3-universal.jar) 
    UC  MCA{1.7.10-5.2.2} [Minecraft Comes Alive](MCA-1.7.10-5.2.2-universal.jar) 
    UC  MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) 
    UE  TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UC  Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) 
    UC  me{1.3.2.1} [More Enchantments](MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UC  AencEx{0.0.1} [AencEx](MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UC  cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UC  NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  neiintegration{1.1.1} [NEI Integration](NEIIntegration-MC1.7.10-1.1.1.jar) 
    UC  PalomitasMod{BETA} [Palomitas Mod](PalomitasMod v2.2.jar) 
    UC  desertcraft{1.7.2b} [Pam's DesertCraft](Pam's DesertCraft 1.7.10a.zip) 
    UC  harvestthenether{1.7.10} [Pam's Harvest the Nether](Pam's Harvest the Nether 1.7.10a.jar) 
    UC  harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10k.jar) 
    UC  simplerecipes{1.7.10a} [Pam's Simple Recipes](Pam's Simple Recipes 1.7.10a.jar) 
    UC  weeeflowers{1.7.2b} [Pam's Weee! Flowers](Pam's WeeeFlowers 1.7.2b.zip) 
    UC  ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UC  TragicMC{2.46.2858} [TragicMC 2](TragicMC2-1.7.10-2.46.2858.jar) 
    UC  tc{4.3.0_003} [Traincraft](Traincraft-4.3.0_003.jar) 
    UC  warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.37.jar) 
    UC  weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) 
    UC  witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.54' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.

**Comment by NitroxydeX** [comment]
@jimmykotaro  Next time paste this inside a Spoiler.

TC has NO Problem with Tinkers. As you can see in your paste UC tc{4.3.0_003}  C stands for constructed while everything related to Tinkers got and UE. E stands for Error. We're not even mentioned in that crashlog.

**Comment by jimmykotaro** [comment]
ok thank you I will go with tinker guys to check it hehe :p , and sorry for the no spoiler but I didnt find the spoiler button :s

**Comment by NitroxydeX** [comment]
@jimmykotaro you need to do it on your own with opening and closing "details" with <>

**Comment by NitroxydeX** [comment]
@jimmykotaro well we "fixed" this now. We just prevent it from crashing. Funny RF Api bug.
