### ISSUE TITLE
Crash when adding blocks to cart storage

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#195]
I think this is a block ID issue going from 1.64 to 1.7.10 . Trying to add blocks to rolling stocks storage causes crash on most cars

This is just a sample crash involving EntityBoxCartUS.java . It happens on other storage cars as well

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/16/16 7:31 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at net.minecraft.inventory.Slot.func_75211_c(Slot.java:67)
    at net.minecraft.inventory.Container.func_75138_a(SourceFile:64)
    at net.minecraft.inventory.Container.func_75132_a(SourceFile:53)
    at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
    at train.common.entity.rollingStock.EntityBoxCartUS.func_130002_c(EntityBoxCartUS.java:101)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:810)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.inventory.Slot.func_75211_c(Slot.java:67)
    at net.minecraft.inventory.Container.func_75138_a(SourceFile:64)
    at net.minecraft.inventory.Container.func_75132_a(SourceFile:53)
    at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
    at train.common.entity.rollingStock.EntityBoxCartUS.func_130002_c(EntityBoxCartUS.java:101)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:810)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@17692064
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_102, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 120290944 bytes (114 MB) / 645296128 bytes (615 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   tc{4.3.0_004} [Traincraft](Traincraft-4.3.0_004.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['MajorPayne181'/136, l='Traincraft Test Track', x=457.31, y=75.00, z=87.52]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by NitroxydeX** [comment]
This is an issue when Playing with DEVELOPEMENT versions,

**Comment by EternalBlueFlame** [comment]
this will be fixed in a commit im working on now.
My fault for trying to fix the referencing in the freight class.

**Comment by EternalBlueFlame** [comment]
fixed as of [https://github.com/EternalBlueFlame/Traincraft-5/commit/e71fbb874107e5f5221ad2b8247cd84808b9bc7c](https://github.com/EternalBlueFlame/Traincraft-5/commit/e71fbb874107e5f5221ad2b8247cd84808b9bc7c)
