### ISSUE TITLE
4.3.1_007 crashed with WorldEdit 

### ISSUE THREAD

**Issue by drzzm32** [EternalBlueFlame/Traincraft-5#242]
When I try to use "stack" command to copy the Small Straight Rail, the server crashed. (I have an server)
Crash reports here:

> java.lang.NullPointerException: Ticking block entity
        at train.common.items.ItemTCRail.isTCSwitch(ItemTCRail.java:112)
        at train.common.tile.TileTCRail.func_145845_h(TileTCRail.java:140)
        at net.minecraft.world.World.func_72939_s(World.java:2529)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)

**Comment by NitroxydeX** [comment]
We mentioned this multiple times before and everyone knows it: WorldEdit has some really big problems with TileEntities like our rails. you can't use the stack command or any commands from WorldEdit to put down any of our TileEntities.

you can see this at the first line "isTCSwitch". It checks something wrong because the data for the TileEntity isn't saved correctly with WorldEdit. Nothing we can do about.

**Comment by drzzm32** [comment]
okay I noticed this problem.

2017年2月3日 21:20，"NitroxydeX" <notifications@github.com>写道：
