### ISSUE TITLE
I have a crash while open the Traincraft mod

### ISSUE THREAD

**Issue by KLS77** [EternalBlueFlame/Traincraft-5#304]
I get a crash report with Release 1.7.10 forge 10.13.4.1558 / 1566 / 1614.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/5/17 12:48 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cpw/mods/fml/common/ITickHandler
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/ITickHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.ITickHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 67283648 bytes (64 MB) / 324976640 bytes (309 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UE	FlansMod{4.1.1} [Flans Mod] (FlansMod-4.1.1.jar) 
	UC	tc{4.3.2_009} [Traincraft] (Traincraft-4.3.2_009.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4364' Renderer: 'Intel(R) HD Graphics 530'

Please help!
Thank you.

**Comment by EternalBlueFlame** [comment]
Your issue is, flans mod 4.1 is for minecraft 1.6.4. not 1.7.10.

also, what's with those JVM fags?
This one specifically does not look legit in any form.
"-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump"
and if you can spare the RAM, this should be at least 1.5, if not 2 or 3 "-Xmx1G"

**Comment by KLS77** [comment]
Hello Jonathan,
I'm doing this for my 10 years boy...Every time he wants a new thing on his Minecraft game, but I am not right in to it...
I have managed to solve it by removing another mod which wasn't compatible with 1.7.10 Forge (flans as you said).I did it in steps.Now it's working and we have one more happy kid. :)
Thank you very much for your quick support!
Best regards,Claudiu


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jonathan <notifications@github.com> Date: 8/5/17  20:03  (GMT+02:00) To: EternalBlueFlame/Traincraft-5 <Traincraft-5@noreply.github.com> Cc: KLS77 <claudiu@eurocom.ro>, Author <author@noreply.github.com> Subject: Re: [EternalBlueFlame/Traincraft-5] I have a crash while open the
  Traincraft mod (#304) 
Your issue is, flans mod 4.1 is for minecraft 1.6.4. not 1.7.10.
also, what's with those JVM fags?

This one specifically does not look legit in any form.

"-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump"

and if you can spare the RAM, this should be at least 1.5, if not 2 or 3 "-Xmx1G"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EternalBlueFlame/Traincraft-5","title":"EternalBlueFlame/Traincraft-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/EternalBlueFlame/Traincraft-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EternalBlueFlame in #304: Your issue is, flans mod 4.1 is for minecraft 1.6.4. not 1.7.10.\r\n\r\nalso, what's with those JVM fags?\r\nThis one specifically does not look legit in any form.\r\n\"-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump\"\r\nand if you can spare the RAM, this should be at least 1.5, if not 2 or 3 \"-Xmx1G\""}],"action":{"name":"View Issue","url":"https://github.com/EternalBlueFlame/Traincraft-5/issues/304#issuecomment-320455047"}}}

**Comment by MggMuggins** [comment]
@EternalBlueFlame I've seen that JVM flag a lot on windows. I'm pretty sure it's set by the launcher by default. I've never seen it on on a *nix system, so I assume it's something that Mojang does.
But I assure you, it's probably legit, because I've seen it on a lot of unrelated systems.

**Comment by EternalBlueFlame** [comment]
Weird. Never seen it on mine, but then again it might actually be related to intel GPU's on windows.
Thanks for the correction. MggMuggins.

At any rate, glad to hear it worked out for you @KLS77 and if your son really wants flans mod you can get 4.9.0 from here, that one should work.
http://www.flansmod.com/download

**Comment by KLS77** [comment]
Could be. The PC is brand new.I still have no separate grafic card, because it is already overbudget... :)I know that the new generation Intel processor is taking care some grafic processing.I am looking for a Gigabyte 1070 as soon as I have the posibility...
Anyway, thanks a lot!
All the best,Claudiu


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jonathan <notifications@github.com> Date: 8/5/17  20:54  (GMT+02:00) To: EternalBlueFlame/Traincraft-5 <Traincraft-5@noreply.github.com> Cc: KLS77 <claudiu@eurocom.ro>, Mention <mention@noreply.github.com> Subject: Re: [EternalBlueFlame/Traincraft-5] I have a crash while open the
  Traincraft mod (#304) 
Weird. Never seen it on mine, but then again it might actually be related to intel GPU's on windows.

Thanks for the correction. MggMuggins.
At any rate, glad to hear it worked out for you @KLS77 and if your son really wants flans mod you can get 4.9.0 from here, that one should work.

http://www.flansmod.com/download

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EternalBlueFlame/Traincraft-5","title":"EternalBlueFlame/Traincraft-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/EternalBlueFlame/Traincraft-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EternalBlueFlame in #304: Weird. Never seen it on mine, but then again it might actually be related to intel GPU's on windows.\r\nThanks for the correction. MggMuggins.\r\n\r\nAt any rate, glad to hear it worked out for you @KLS77 and if your son really wants flans mod you can get 4.9.0 from here, that one should work.\r\nhttp://www.flansmod.com/download"}],"action":{"name":"View Issue","url":"https://github.com/EternalBlueFlame/Traincraft-5/issues/304#issuecomment-320459973"}}}

**Comment by EternalBlueFlame** [comment]
It would be a lot cheaper to get one of the 4gb EVGA 1050's, and you wouldn't see any performance difference unless you are playing forza horizon 3.
