### ISSUE TITLE
Latest compile causes game crash on world load Aug 19 

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#414]
+Traced problem to commit 4711812fafbfe65404ac37c236f8f78de7ae017d

-- Minecra-ft Crash Report ----
// Ouch. That hurt :(

Time: 19/08/18 2:34 PM
Description: Ticking entity

io.netty.handler.codec.EncoderException: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at cpw.mods.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:48)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:123)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:471)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:359)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:336)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:284)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at net.minecraft.entity.DataWatcher.func_151510_a(SourceFile:223)
	at net.minecraft.entity.DataWatcher.func_151509_a(SourceFile:186)
	at cpw.mods.fml.common.network.internal.FMLMessage$EntitySpawnMessage.toBytes(FMLMessage.java:197)
	at cpw.mods.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:22)
	at cpw.mods.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:11)
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at cpw.mods.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:48)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:123)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:471)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:359)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:336)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:284)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 448
	Entity Name: MajorPayne181
	Entity's Exact location: 366.81, 82.69, 196.35
	Entity's Block location: World: (366,82,196), Chunk: (at 14,5,4 in 22,12; contains blocks 352,0,192 to 367,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Traincraft Test Track 1.7.10
	All players: 1 total; [EntityPlayerMP['MajorPayne181'/448, l='Traincraft Test Track 1.7.10', x=366.81, y=82.69, z=196.35]]
	Chunk stats: ServerChunkCache: 1141 Drop: 0
	Level seed: 8653760367652333124
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (257,69,186), Chunk: (at 1,4,10 in 16,11; contains blocks 256,0,176 to 271,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6059272 game time, 540222 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57514 (now: false), thunder time: 102480 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.15.0-32-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 429235080 bytes (409 MB) / 738197504 bytes (704 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 19, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	tc{4.4.0_018} [Traincraft] (Traincraft-4.4.0_018_4711812fafbfe65404ac37c236f8f78de7ae017d.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['MajorPayne181'/448, l='Traincraft Test Track 1.7.10', x=366.81, y=82.69, z=196.35]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Tsoccerguy3** [comment]
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at net.minecraft.entity.DataWatcher.func_151510_a(SourceFile:223)
	at net.minecraft.entity.DataWatcher.func_151509_a(SourceFile:186)

**Comment by Tsoccerguy3** [comment]
will look for error later

It's in  src/main/java/train/common/library/EnumTrains.java

**Comment by EternalBlueFlame** [comment]
Your tracking "skills" need work.
None of the changes in the code at that commit, or even that entire class are related to the datawatcher.

i'll doublecheck the datawatcher uses and see if there's an integer datawatcher getting a float, but this could be anything, in fact even some versions of thermos and forge have this issue without mods.

**Comment by Tsoccerguy3** [comment]
all I can See is the previous commit does not crash the game . I can't make sense of it either

**Comment by Tsoccerguy3** [comment]
Your right I was going backwards to find the last commit that worked

So the last commit that worked was 5f61bfeecdb5be7d31e0f212fc3c64a9d4946207

just double checked

**Comment by EternalBlueFlame** [comment]
Well, thanks for the crashlog and testing if it worked, that's the stuff that REALLY makes a difference with this stuff.

**Comment by Tsoccerguy3** [comment]
Yes , It now works fine
