### ISSUE TITLE
incompatibility of traincraft and railcraft rails

### ISSUE THREAD

**Issue by Raffo15** [EternalBlueFlame/Traincraft-5#688]
Good morning everyone, 
I am writing to point out the fact that many Traincraft models have problems running on special Railcraft rails. On my server I use them as sensors in some particular points for signaling, placing them in the middle of the traincraft tracks. With the **latest update** only locomotives are able to cross them, and many carriages or wagons stop before them as if they do not detect the track.
what can I do? do I need to change the type of sensor? it would be a big job for me because I would have to modify many routes on the map

**Comment by EternalBlueFlame** [comment]
just to be sure, when you say the latest version, do you mean from curseforge, or the build artifacts from here on git?

I remember this issue being brought up before and, _I may be wrong_, but I think there were fixes for it already in place on git.
Here's a shortcut link for the latest build artifact if you want to test that, assuming you haven't already. If this is the version you meant, I apologize for the misunderstanding.
[https://nightly.link/EternalBlueFlame/Traincraft-5/workflows/gradle/TC4.5-1.7.10/TC4-5-Experimental.zip](https://nightly.link/EternalBlueFlame/Traincraft-5/workflows/gradle/TC4.5-1.7.10/TC4-5-Experimental.zip)

**Comment by Raffo15** [comment]
Hi, I mean the curseforge version "4.4.1_020-CE_7.1". I think is the latest on curseforge.

**Comment by sterilija** [comment]
Agreed with the topic author, I have the same issue when starting a server, my crash report: 


> 
> ---- Minecraft Crash Report ----
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 1/21/25 11:37 AM
> Description: Exception in server tick loop
> 
> java.lang.NullPointerException: Exception in server tick loop
> 	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:39)
> 	at train.common.core.plugins.PluginRailcraft.registerRecipes(PluginRailcraft.java:25)
> 	at train.common.core.plugins.PluginRailcraft.init(PluginRailcraft.java:19)
> 	at train.common.core.TrainModCore.ModsLoaded(TrainModCore.java:38)
> 	at train.common.Traincraft.postInit(Traincraft.java:269)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
> 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
> 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
> 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
> 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
> 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
> 	Plugins: 
> 	Disabled Plugins: 
> 	Operating System: Windows 10 (x86) version 10.0
> 	Java Version: 1.8.0_431, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
> 	Memory: 494837024 bytes (471 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
> 	JVM Flags: 1 total; -Xms1024M
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 78 mods loaded, 78 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (Thermos-1.7.10-1614-server.jar) 
> 	UCHIJ	Forge{10.13.4.1614} [Minecraft Forge] (Thermos-1.7.10-1614-server.jar) 
> 	UCHIJ	kimagine{0.2} [KImagine] (minecraft.jar) 
> 	UCHIJ	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
> 	UCHIJ	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core_1.7.10_1.0.2.16.jar) 
> 	UCHIJ	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
> 	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
> 	UCHIJ	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
> 	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
> 	UCHIJ	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
> 	UCHIJ	BuildCraft|Core{7.1.25} [BuildCraft] (buildcraft-7.1.25.jar) 
> 	UCHIJ	BuildCraft|Silicon{7.1.25} [BC Silicon] (buildcraft-7.1.25.jar) 
> 	UCHIJ	BuildCraft|Transport{7.1.25} [BC Transport] (buildcraft-7.1.25.jar) 
> 	UCHIJ	BuildCraft|Factory{7.1.25} [BC Factory] (buildcraft-7.1.25.jar) 
> 	UCHIJ	additionalpipes{4.7.7} [Additional Pipes] (additionalpipes-4.7.7.jar) 
> 	UCHIJ	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
> 	UCHIJ	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel_1.7.10_Edition.jar) 
> 	UCHIJ	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
> 	UCHIJ	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core_1.7.10_1.0.2.16.jar) 
> 	UCHIJ	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
> 	UCHIJ	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.5][MC1.7.10].jar) 
> 	UCHIJ	BuildCraft|Builders{7.1.25} [BC Builders] (buildcraft-7.1.25.jar) 
> 	UCHIJ	BuildCraft|Robotics{7.1.25} [BC Robotics] (buildcraft-7.1.25.jar) 
> 	UCHIJ	BuildCraft|Energy{7.1.25} [BC Energy] (buildcraft-7.1.25.jar) 
> 	UCHIJ	ChickenChunks{1.3.4.16} [ChickenChunks] (chickenchunks-1.7.10-1.3.4.16.jar) 
> 	UCHIJ	Railcraft{9.12.2.1} [Railcraft] (railcraft_1.7.10-9.12.2.1.jar) 
> 	UCHIJ	TwilightForest{2.4.3} [The Twilight Forest] (TwilightForest-2.4.3.jar) 
> 	UCHIJ	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
> 	UCHIJ	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
> 	UCHIJ	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
> 	UCHIJ	comboarmors{1.7.10-0.0.3} [Combo Armors] (comboarmors-1.7.10-0.0.3.jar) 
> 	UCHIJ	CompactWindmills{1.0.3.1} [CompactWindmills] (CompactWindmills-1.7.2-1.0.3.1.jar) 
> 	UCHIJ	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
> 	UCHIJ	endercore{1.7.10-0.2.0.40_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.40_beta.jar) 
> 	UCHIJ	EnderIO{1.7.10-2.3.0.430_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.430_beta.jar) 
> 	UCHIJ	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (Thermal_Foundation.jar) 
> 	UCHIJ	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
> 	UCHIJ	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
> 	UCHIJ	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (mantle-1.7.10-0.3.2b.jar) 
> 	UCHIJ	ImmersiveEngineering{0.7.7} [Immersive Engineering] (immersive-engineering-mod-1.7.10-1.jar) 
> 	UCHIJ	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (thermalexpansion-1.7.104.1.5-248.jar) 
> 	UCHIE	tc{4.5.0} [Traincraft] (Traincraft-4.5.0_001.jar) 
> 	UCHIJ	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (tconstruct-1.7.10-1.8.8.build991.jar) 
> 	UCHIJ	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
> 	UCHIJ	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
> 	UCHIJ	GalaxySpace{1.2.14 Pre-Final} [GalaxySpace] (GalaxySpace_1.7.10_1.2.14.jar) 
> 	UCHIJ	gendustry{1.6.4.135} [GenDustry] (gendustry-1.6.4.135-mc1.7.10.jar) 
> 	UCHIJ	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
> 	UCHIJ	Highlands{2.2.0} [Highlands] (highlands_1.7.2_v_2.2.1.jar) 
> 	UCHIJ	IC2NuclearControl{2.4.3a} [Nuclear Control 2] (IC2NuclearControl-2.4.3a.jar) 
> 	UCHIJ	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
> 	UCHIJ	JABBA{1.1.4} [JABBA] (just_another_better_barrel_attempt_mod_1.7.10.jar) 
> 	UCHIJ	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
> 	UCHIJ	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
> 	UCHIJ	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
> 	UCHIJ	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
> 	UCHIJ	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
> 	UCHIJ	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
> 	UCHIJ	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (projectred-1.7.10-4.7.0pre12.95-base.jar) 
> 	UCHIJ	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (projectred-1.7.10-4.7.0pre12.95-integration.jar) 
> 	UCHIJ	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (projectred-1.7.10-4.7.0pre12.95-mechanical.jar) 
> 	UCHIJ	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (projectred-1.7.10-4.7.0pre12.95-world.jar) 
> 	UCHIJ	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (projectred-1.7.10-4.7.0pre12.95-compat.jar) 
> 	UCHIJ	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (projectred-1.7.10-4.7.0pre12.95-integration.jar) 
> 	UCHIJ	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (projectred-1.7.10-4.7.0pre12.95-fabrication.jar) 
> 	UCHIJ	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (projectred-1.7.10-4.7.0pre12.95-lighting.jar) 
> 	UCHIJ	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (projectred-1.7.10-4.7.0pre12.95-mechanical.jar) 
> 	UCHIJ	TallDoors{0.5.1} [Tall Doors Mod] (Tall_Doors_Mod_1.7.10.jar) 
> 	UCHIJ	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (thermaldynamics-1.7.101.2.1-172.jar) 
> 	UCHIJ	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
> 	UCHIJ	Treecapitator{1.7.10} [Treecapitator] (treecapitator.jar) 
> 	UCHIJ	WaterPower{0.3u} [WaterPower] (WaterPower_1.7.10_0.3u.jar) 
> 	UCHIJ	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
> 	UCHIJ	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
> 	UCHIJ	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
> 	UCHIJ	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
> 	UCHIJ	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
> 	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
> 	Class transformer null safety: all safe
> 	CoFHCore: -[1.7.10]3.1.4-329
> 	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
> 	ThermalFoundation: -[1.7.10]1.2.6-118
> 	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
> 	ThermalExpansion: -[1.7.10]4.1.5-248
> 	TConstruct Environment: Environment healthy.
> 	ThermalDynamics: -[1.7.10]1.2.1-172
> 	List of loaded APIs: 
> 		* apAPI (2) from additionalpipes-4.7.7.jar
> 		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
> 		* Baubles|API (1.0.1.10) from Thermal_Foundation.jar
> 		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|core (1.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* BuildCraftAPI|crops (1.1) from railcraft_1.7.10-9.12.2.1.jar
> 		* BuildCraftAPI|events (2.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|items (1.1) from railcraft_1.7.10-9.12.2.1.jar
> 		* BuildCraftAPI|library (2.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|power (1.3) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|recipes (3.1) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|tiles (1.2) from railcraft_1.7.10-9.12.2.1.jar
> 		* BuildCraftAPI|tools (1.0) from buildcraft-7.1.25.jar
> 		* BuildCraftAPI|transport (4.1) from railcraft_1.7.10-9.12.2.1.jar
> 		* ChiselAPI (0.1.1) from Chisel-2.9.4.10.jar
> 		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.4.10.jar
> 		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.4.10.jar
> 		* CoFHAPI (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHAPI|block (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHAPI|energy (1.7.10R1.3.1) from Traincraft-4.5.0_001.jar
> 		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHAPI|inventory (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* CoFHAPI|item (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHAPI|transport (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|gui (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|gui|container (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|gui|slot (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|render|particle (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|util|helpers (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|util|position (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|world (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* CoFHLib|world|feature (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
> 		* ComputerCraft|API (1.75) from Traincraft-4.5.0_001.jar
> 		* ComputerCraft|API|FileSystem (1.75) from Traincraft-4.5.0_001.jar
> 		* ComputerCraft|API|Lua (1.75) from ComputerCraft1.75.jar
> 		* ComputerCraft|API|Media (1.75) from ComputerCraft1.75.jar
> 		* ComputerCraft|API|Peripheral (1.75) from Traincraft-4.5.0_001.jar
> 		* ComputerCraft|API|Permissions (1.75) from ComputerCraft1.75.jar
> 		* ComputerCraft|API|Redstone (1.75) from ComputerCraft1.75.jar
> 		* ComputerCraft|API|Turtle (1.75) from ComputerCraft1.75.jar
> 		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
> 		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.16.64.jar
> 		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-1.7.10-0.0.1.4-universal.jar
> 		* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.504.jar
> 		* gendustryAPI (2.3.0) from gendustry-1.6.4.135-mc1.7.10.jar
> 		* IC2API (1.0) from industrialcraft-2-2.2.827-experimental.jar
> 		* ImmersiveEngineering|API (1.0) from immersive-engineering-mod-1.7.10-1.jar
> 		* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.1.1.1031.jar
> 		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.4.3a.jar
> 		* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.6.jar
> 		* RailcraftAPI|bore (1.0.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* RailcraftAPI|carts (1.6.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* RailcraftAPI|core (1.5.0) from Traincraft-4.5.0_001.jar
> 		* RailcraftAPI|crafting (1.0.0) from Traincraft-4.5.0_001.jar
> 		* RailcraftAPI|electricity (2.0.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* RailcraftAPI|events (1.0.0) from Traincraft-4.5.0_001.jar
> 		* RailcraftAPI|fuel (1.0.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* RailcraftAPI|helpers (1.1.0) from Traincraft-4.5.0_001.jar
> 		* RailcraftAPI|items (1.0.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* RailcraftAPI|locomotive (1.1.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* RailcraftAPI|signals (2.3.0) from railcraft_1.7.10-9.12.2.1.jar
> 		* RailcraftAPI|tracks (2.3.0) from Traincraft-4.5.0_001.jar
> 		* Thaumcraft|API (4.2.2.0) from railcraft_1.7.10-9.12.2.1.jar
> 	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
> 	EnderIO: Found the following problem(s) with your installation:
>                   * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
>                     Ender IO was build against API version rv2 and may or may not work with a newer version.
>                  An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported.
>                  This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
> 	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
> Bukkit, Cauldron, or other Bukkit replacement
> These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
> 	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
> 	Profiler Position: N/A (disabled)
> 	Player Count: 0 / 20; []
> 	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
> 	Type: Dedicated Server (map_server.txt)
>

**Comment by sterilija** [comment]
I have found only this dialogue about the problem:
https://cursefire.com/minecraft/mc-mods/traincraft/issues/184

I don't understand what vanilla recipes the developer means there, if you have any idea about it, please, help us

**Comment by chiel1112** [comment]
This is not the same error. Please for next time make your own issue thread.

In the meantime in /config/forge.cfg try enabling "remove erroring entities" and "remove erroring tile entities". This could fix your problem and make your server at least boot again, although it may remove some trains or track

**Comment by sterilija** [comment]
thank you for helping, unfortunately, these config lines didnt fix this problem, the crashReport stackTrace is the same after multiple server restarts

**Comment by chiel1112** [comment]
This may sound silly but are you sure you saved the config file after editing?

Forgot to save it myself a couple of times🙈

**Comment by sterilija** [comment]
yes i rechecked it two times, it has both true on these options, anyway thank you for bumping this issue

**Comment by EternalBlueFlame** [comment]
> Agreed with the topic author, I have the same issue when starting a server, my crash report:
> 
> > ---- Minecraft Crash Report ----
> > // Hi. I'm Minecraft, and I'm a crashaholic.
> > Time: 1/21/25 11:37 AM
> > Description: Exception in server tick loop
> > java.lang.NullPointerException: Exception in server tick loop
> > at net.minecraftforge.oredict.ShapedOreRecipe.(ShapedOreRecipe.java:39)


not only is this a different issue from the OP, and the other issue linked, but something in your modpack is changing how ShapedOreRecipe defines recipes. In both normal forge and thermos, line 39 doesn't have any code, line 38 and 40 are relying on internal code and not what is provided by Traincraft, and so could not have a null pointer exception.

I've pushed a small change just now that should fix any remaining potential nulls from our end, if the issue persists then it's neither Traincraft or Railcraft and this needs it's own thread to figure out what mod is causing the problem.

The config entry previously mentioned is `useAltRecipes` in the railcraft config, however if this is enabled, it disables a number of integrations between Traincraft and Railcraft.
